name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LINES_OF_CODE: "True"
